# Override these attribute values in this environment specific configuration.

[application]
google_project_id = "${project_id}"

[storage]
high_res_input_bucket = "${high_res_input_bucket}"
low_res_output_bucket = "${low_res_output_bucket}"
